//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANVESO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAILI
    {
        public string MaDL { get; set; }
        public string TenDL { get; set; }
        public string DiaChi { get; set; }
        public string Sdt { get; set; }
    
        public virtual DANGKISOLUONG DANGKISOLUONG { get; set; }
    }
}
