//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANVESO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKISOLUONG
    {
        public string MaDL { get; set; }
        public string SoLuongDK { get; set; }
        public Nullable<System.DateTime> NgayDK { get; set; }
    
        public virtual DAILI DAILI { get; set; }
    }
}
